CREATE TABLE [MRU] (
  [MRU_ID] AUTOINCREMENT CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL,
  [EmployeeID] LONG CONSTRAINT [New_New_EmployeesMRU] REFERENCES [Employees] ([EmployeeID]) ON DELETE CASCADE ,
  [TableName] VARCHAR (50),
  [PKValue] LONG,
  [DateAdded] DATETIME,
   CONSTRAINT ,
   CONSTRAINT 
)
